#table as an option is displayed under the help command
#category.explain under each table as the description of that table
#A command consists of four parts, namely. Name, explain, template, how_to_use, unfilled will be displayed "é€™è£¡æ²’æœ‰ç•™ä¸‹ä»€éº¼ã€‚"
#ğŸ”§Server administrator onlyï¼ŒğŸªªBot owners onlyï¼ŒğŸš¹Available when applied personallyï¼ŒğŸ” has a search functionï¼ŒğŸª§The bot's responses can be seen by others"
[Manage]
category.explain = "èˆ‡æ©Ÿå™¨äººç®¡ç†æˆ–æ¸¬è©¦æœ‰é—œçš„æŒ‡ä»¤ã€‚"

cogs_load.explain = "ğŸªª ğŸ”è¼‰å…¥é¸æ“‡çš„cogsã€‚"
cogs_load.template = "/cogs load Help"
cogs_load.how_to_use = "/cogs load <é½’è¼ªåç¨±>"

cogs_unload.explain = "ğŸªª ğŸ”å¸è¼‰é¸æ“‡çš„cogsã€‚"
cogs_unload.template = "/cogs unload Help"
cogs_unload.how_to_use = "/cogs unload <é½’è¼ªåç¨±>"

cogs_reload.explain = "ğŸªª ğŸ”é‡æ–°è¼‰å…¥é¸æ“‡çš„cogsã€‚"
cogs_reload.template = "/cogs reload Help"
cogs_reload.how_to_use = "/cogs reload <é½’è¼ªåç¨±>"

cogs_show.explain = "ğŸªª ğŸ”é¡¯ç¤ºæ‰€æœ‰å·²è¼‰å…¥çš„cogsã€‚"
cogs_show.template = "/cogs show"
cogs_show.how_to_use = "/cogs show"

info_bot.explain = "ğŸš¹æŸ¥çœ‹æ©Ÿå™¨äººçš„éƒ¨åˆ†è³‡è¨Šï¼ŒåŒ…æ‹¬CPUä½¿ç”¨ç‡ã€è¨˜æ†¶é«”ä½¿ç”¨ç‡ã€ç¡¬ç¢Ÿä½¿ç”¨ç‡ã€ç•¶å‰ç¶²è·¯æ”¶ç™¼é€Ÿåº¦ã€å•Ÿå‹•æ—¥æœŸã€æ‰€åœ¨ä¼ºæœå™¨æ•¸é‡ã€‚"
info_bot.template = "/info_bot"
info_bot.how_to_use = "/info_bot"

ping.explain = "ğŸš¹æ¸¬è©¦æ©Ÿå™¨äººç›®å‰èˆ‡discordçš„å»¶é²ã€‚"
ping.template = "/ping"
ping.how_to_use = "/ping"

invitation.explain = "ğŸš¹ ğŸª§ç²å–æ©Ÿå™¨äººçš„é‚€è«‹é€£çµã€‚"
invitation.template = "/invitation"
invitation.how_to_use = "/invitation"

help.explain = "ğŸš¹ä¾ç…§Helpçš„å…§å®¹æä¾›å¹«åŠ©ã€‚"
help.template = "/help"
help.how_to_use = "/help"

[Poll]
category.explain = "é—œæ–¼æŠ•ç¥¨çš„æŒ‡ä»¤ã€‚"

create_poll.explain = "ğŸ”§ ğŸª§å‰µå»ºä¸€å€‹æŠ•ç¥¨ã€‚"
create_poll.template = "/create_poll poll1 A,B,C,D"
create_poll.how_to_use = "/create_poll <æŠ•ç¥¨åç¨±> <æŠ•ç¥¨é¸é …> [çµæŸæ™‚é–“(é è¨­1å¤©)] [å¯åƒèˆ‡æŠ•ç¥¨çš„ä½¿ç”¨è€…(é è¨­æ‰€æœ‰äºº)]"

[Music]
category.explain = "é—œæ–¼éŸ³æ¨‚çš„æŒ‡ä»¤ã€‚"

music_play.explain = "ğŸ”å¯è¼¸å…¥åç¨±å¾Œæœå°‹å°æ‡‰åç¨±çš„éŸ³æ¨‚æä¾›é¸æ“‡ï¼Œæˆ–æ˜¯ç›´æ¥ä»¥é€£æ¥æ’­æ”¾ã€‚"
music_play.template = "/music play never"
music_play.how_to_use = "/music play <åç¨±æˆ–é€£çµ>"

music_volume.explain = "ä»¥ç™¾åˆ†æ¯”èª¿æ•´éŸ³æ¨‚æ’­æ”¾éŸ³é‡ï¼Œç¯„åœ0-150ï¼Œåˆå§‹éŸ³é‡ç”±Settingçš„Volumeæ±ºå®šã€‚"
music_volume.template = "/music volume 50"
music_volume.how_to_use = "/music volume <0-150>"

music_queue.explain = "é¡¯ç¤ºç•¶å‰æ’­æ”¾åˆ—è¡¨ä¸¦æä¾›ç”¨æ–¼æ§åˆ¶éŸ³æ¨‚æ’­æ”¾çš„æŒ‰éˆ•ã€‚"
music_queue.template = "/music queue"
music_queue.how_to_use = "/music queue"

music_pause.explain = "æš«åœç•¶å‰æ’­æ”¾çš„éŸ³æ¨‚ã€‚"
music_pause.template = "/music pause"
music_pause.how_to_use = "/music pause"

music_resume.explain = "æ¢å¾©æš«åœçš„éŸ³æ¨‚ã€‚"
music_resume.template = "/music resume"
music_resume.how_to_use = "/music resume"

music_stop.explain = "çµ‚æ­¢éŸ³æ¨‚æ’­æ”¾ä¸¦æ¸…ç©ºæ’­æ”¾åˆ—è¡¨ã€‚"
music_stop.template = "/music stop"
music_stop.how_to_use = "/music stop"

music_skip.explain = "è·³éç•¶å‰æ’­æ”¾çš„éŸ³æ¨‚ã€‚"
music_skip.template = "/music skip"
music_skip.how_to_use = "/music skip"

music_remove.explain = "å¾æ’­æ”¾åˆ—è¡¨ä¸­ç§»é™¤æŒ‡å®šçš„éŸ³æ¨‚ã€‚"
music_remove.template = "/music remove 1"
music_remove.how_to_use = "/music remove <éŸ³æ¨‚ç·¨è™Ÿ>"

music_random.explain = "å¾ä¸‹ä¸€é¦–é–‹å§‹æ‰“äº‚æ’­æ”¾çš„é †åºã€‚"
music_random.template = "/music random"
music_random.how_to_use = "/music random"

music_play_index.explain = "ç«‹å³æ’­æ”¾æŒ‡å®šçš„éŸ³æ¨‚ä¸¦åˆªé™¤ç•¶å‰æ’­æ”¾çš„éŸ³æ¨‚ã€‚"
music_play_index.template = "/music play_index 1"
music_play_index.how_to_use = "/music play_index <éŸ³æ¨‚ç·¨è™Ÿ>"

[Message]
category.explain = "ç®¡ç†æ–‡å­—æˆ–èˆ‡æ–‡å­—è¼ƒç›¸é—œçš„æŒ‡ä»¤ã€‚"

mc_status.explain = "ğŸš¹æŸ¥çœ‹Minecraftä¼ºæœå™¨ç‹€æ…‹ã€‚"
mc_status.template = "/mc_status example.com"
mc_status.how_to_use = "/mc_status <ä¼ºæœå™¨åœ°å€> [ä¼ºæœå™¨ç«¯å£(é è¨­25565)]"

delete_msg.explain = "ğŸ”§åˆªé™¤é »é“ä¸­çš„è¨Šæ¯ã€‚"
delete_msg.template = "/delete_msg 5"
delete_msg.how_to_use = "/delete_msg <è¦åˆªé™¤çš„è¨Šæ¯æ•¸é‡>"

notebook.explain = "ğŸš¹è®“æ©Ÿå™¨äººç§è¨Šä½ ä¾†å‘ˆç¾ä¸€å€‹è¨˜äº‹æœ¬ã€‚"
notebook.template = "/notebook"
notebook.how_to_use = "/notebook"

buy_or_not.explain = "ğŸš¹éš¨æ©Ÿå›è¦†Buy_OR_Notå…§çš„é¸é …ã€‚"
buy_or_not.template = "/buy_or_not"
buy_or_not.how_to_use = "/buy_or_not"

word_changer.explain = "ğŸš¹å°æŒ‡å®šæ–‡å­—é€²è¡Œæ›¿æ›ã€‚"
word_changer.template = "/word_changer hello_world world bot"
word_changer.how_to_use = "/word_changer <è¦ä¿®æ”¹çš„æ–‡æœ¬> <é¸å®šçš„æ–‡å­—> <æ›¿æ›çš„æ–‡å­—>"

[Image]
category.explain = "èˆ‡åœ–ç‰‡è¼ƒç›¸é—œçš„æŒ‡ä»¤ã€‚"

called_figure.explain = "ğŸš¹ ğŸ” ğŸª§å¾æ©Ÿå™¨äººå…§æœå°‹ä¸¦è²¼ä¸Šå°æ‡‰çš„åœ–ç‰‡ï¼Œæœå°‹åŠŸèƒ½ä¸€æ¬¡æœ€å¤šé¡¯ç¤º25å€‹ï¼Œå¦‚æœæœªé¡¯ç¤ºå¯ä»¥æŠŠé—œéµå­—æ‰“é•·é»ã€‚"
called_figure.template = "/called_figure ä¸éœ€è¦å¦³æ“”å¿ƒ"
called_figure.how_to_use = "/called_figure <åå­—>"

anime_search.explain = "ğŸš¹ æ ¹æ“šå‹•æ¼«æˆªåœ–æœå°‹è©²æˆªåœ–çš„ç›¸é—œè³‡æ–™ï¼ŒåŒ…æ‹¬å‹•æ¼«åã€é›†æ•¸ã€å‡ºç¾çš„æ™‚é–“ï¼Œæ”¯æ´åœ–ç‰‡æª”è·Ÿé€£çµï¼Œå¦‚æœåŒæ™‚çµ¦äºˆå…©è€…å‰‡æ˜¯åœ–ç‰‡æª”å„ªå…ˆ"
anime_search.template = "/anime_search image.png"
anime_search.how_to_use = "/anime_search [åœ–ç‰‡æª”æ¡ˆ] [åœ–ç‰‡é€£çµ]"

[Gemini]
category.explain = "é—œæ–¼geminiçš„æŒ‡ä»¤ã€‚"

tag_nuru.explain = "ğŸš¹ ğŸª§@nuruä¸¦åŠ ä¸Šè¦å‚³é€çš„è¨Šæ¯nuruå°±æœƒå›ç­”ä½ ï¼Œnuruå¯ä»¥å›ç­”æ–‡å­—ä¸¦çœ‹çš„è¦‹å‚³å‡ºçš„åœ–åƒã€‚"
tag_nuru.template = "@nuru hello"
tag_nuru.how_to_use = "@nuru <è¨Šæ¯>"

gemini_reset.explain = "ğŸš¹æ¸…ç©ºgeminièˆ‡ä½ çš„æ­·å²å°è©±ç´€éŒ„"
gemini_reset.template = "/gemini_reset"
gemini_reset.how_to_use = "/gemini_reset"

gemini_private.explain = "ğŸªªè¨­å®šgeminiåœ¨ç§è¨Šæ™‚æœƒä¸æœƒè¢«è§¸ç™¼"
gemini_private.template = "/gemini_private off"
gemini_private.how_to_use = "/gemini_private <on/off>"

[Channel]
category.explain = "èª¿æ•´é »é“æˆ–æ˜¯èº«åˆ†çµ„çš„æŒ‡ä»¤ã€‚"

dynamic_voice_add_voice.explain = "ğŸ”§æ–°å¢ä¸€å€‹å‹•æ…‹èªéŸ³é »é“ï¼Œåœ¨ä½¿ç”¨è€…é€²å…¥æ¯é »é“å¾Œå°‡æœƒå‰µå»ºä¸€å€‹å­é »é“ä¸¦æŠŠä½¿ç”¨è€…ç§»å…¥ï¼Œè€Œå­é »é“æœƒåœ¨æ‰€æœ‰ä½¿ç”¨è€…é›¢é–‹å¾Œè‡ªå‹•åˆªé™¤ã€‚"
dynamic_voice_add_voice.template = "/dynamic_voice add_voice dynamic"
dynamic_voice_add_voice.how_to_use = "/dynamic_voice add_voice <æ¯é »é“åç¨±>"

dynamic_voice_remove_voice.explain = "ğŸ”§ ğŸ”ç§»é™¤ä¸€å€‹å‹•æ…‹èªéŸ³é »é“ã€‚"
dynamic_voice_remove_voice.template = "/dynamic_voice remove_voice dynamic"
dynamic_voice_remove_voice.how_to_use = "/dynamic_voice remove_voice <æ¯é »é“åç¨±>"

dynamic_voice_set_voice_template.explain = "ğŸ”§ ğŸ”è¨­å®šå‹•æ…‹èªéŸ³å­é »é“åç¨±æ¨¡ç‰ˆï¼Œåç¨±å…§å‡ºç¾{}å‰‡æœƒå°‡{}æ›¿æ›ç‚ºç¬¬ä¸€å€‹é€²å…¥è©²é »é“çš„ä½¿ç”¨è€…åç¨±ï¼Œå¦‚æœä¸é€²è¡Œè¨­å®šåˆå§‹åç¨±ç‚º {}çš„å‹•æ…‹èªéŸ³ã€‚"
dynamic_voice_set_voice_template.template = "/dynamic_voice set_voice_template dynamic {}çš„å‹•æ…‹èªéŸ³"
dynamic_voice_set_voice_template.how_to_use = "/dynamic_voice set_voice_template <æ¯é »é“åç¨±> <å­é »é“åç¨±æ¨¡æ¿>"

move_voice.explain = "ğŸ”§ ğŸ”å°‡æŒ‡å®šé »é“å…§çš„æ‰€æœ‰ä½¿ç”¨è€…ç§»å‹•åˆ°å…¶ä»–é »é“ã€‚"
move_voice.template = "/move_voice voice1 voice2"
move_voice.how_to_use = "/move_voice <ä¾†æºé »é“åç¨±> <ç›®æ¨™é »é“åç¨±>"

create_role.explain = "ğŸ”§å»ºç«‹ä¸€å€‹èº«åˆ†çµ„ä¸¦å‰µå»ºå°æ‡‰çš„æ–‡å­—å’ŒèªéŸ³é »é“ï¼Œé »é“åç¨±èˆ‡èº«åˆ†çµ„åç¨±ç›¸åŒã€‚"
create_role.template = "/create_role role1"
create_role.how_to_use = "/create_role <èº«åˆ†çµ„åç¨±>"